### ISSUE TITLE
ALS V4 Replicated problem!!!!

### ISSUE THREAD

**Issue by Akiinow** [nathanmiguel123/ALSReplicated#1]
1- A problem with the movement of the foot (server)
2- Roll problem upon completion of player animation (server)
3- The server does not display the client Sprint animation (server)
4- A problem in Ragdoll Is moving (Client)
5- Problem in using platform and that platform is not replicated, what is causing the problem (server) (Client)
(But the player stands on the platform without problem in (server) )
6- When the player climbs one of the platforms and moves immediately after the climb is over, a foot problem occurs (Client)
(In short it is to hold down W when the player climbs up)
7- A problem when the player in the server do Ragdoll As the problem appears to Client only (server) 
8- A problem when turning around quickly and in your hand the weapon and the turn in place gltich  (server)

**Comment by nathanmiguel123** [comment]
Problams fixed 
3, 5

**Comment by dEROZA** [comment]
> Problams fixed
> 3, 5
lol, if you calculate float points, usage math function pls. especially for framerate space..

**Comment by nathanmiguel123** [comment]
I made some changes to remove the lag, I need you to test again and tell me what problems continue to persist

@dEROZA  I will close this report, you could try again and see if the problem persists. If yes open a new topic ok.
