### ISSUE TITLE
incorrect speed sync 

### ISSUE THREAD

**Issue by dEROZA** [nathanmiguel123/ALSReplicated#2]
Pls, review  the player movement speed changer..
Needed in additional Network Smoothing configuration if can't be solved via BP
What do you think about it?

**Comment by nathanmiguel123** [comment]
![image](https://user-images.githubusercontent.com/29849613/84604380-03b33a80-ae6c-11ea-836f-c2814e7e8f3d.png)
Now i fix the speed sync
![image](https://user-images.githubusercontent.com/29849613/84604397-25142680-ae6c-11ea-8ea1-c4356a5b6c02.png)

**Comment by nathanmiguel123** [comment]
i will close this issues after update

**Comment by dEROZA** [comment]
And what you show? Check when working diff at often forward vector changes? Right Left running, run-walk switches at different forwarding and you see how works logics and cause freezing.
