### ISSUE TITLE
Problems With The New One

### ISSUE THREAD

**Issue by Akiinow** [nathanmiguel123/ALSReplicated#3]
1-Turn In Place ( Client ) 
2-Roll problem upon completion of player animation (server)
3-Roll Lag ( Client )
4- Jump Animation Not Show to Client ( Client )
5-A problem in Ragdoll Is moving (Client) ( Server )
6- When the player climbs one of the Wall and moves immediately after the climb is over, a foot problem occurs (Client)
(In short it is to hold down W when the player climbs up)
7-If you Crouch in Client you Will See Turn In Place Work Good ( Client ) But When you do it in Server it is not good ( Server )
8-That Problem i show it to you when you jump there is glitch in The Foot ( Server )

**Comment by nathanmiguel123** [comment]
now its fix
