### ISSUE TITLE
Projectile fired does not follow line trace

### ISSUE THREAD

**Issue by Nash32x** [nathanmiguel123/ALSReplicated#4]
Projectiles do not tend to follow the line trace end/hit destination on clients.

**Comment by nathanmiguel123** [comment]
![unknown](https://user-images.githubusercontent.com/29849613/85210693-83cc1b00-b318-11ea-98c5-6106497edb04.png)
![unknown (1)](https://user-images.githubusercontent.com/29849613/85210694-875fa200-b318-11ea-9d95-d3d137bd7efa.png)
try this, its work on lient and server
